# Sandbox: Extract Codes and mas and aas

Playing around with other important entities in MERCS

## Preliminaries

### External Imports

In [1]:
import numpy as np
import os
import sys
from sklearn.metrics import (mean_absolute_error,
                             mean_squared_error,
                             mean_squared_log_error)
import pandas as pd

### MERCS imports

In [2]:
sys.path.insert(0, '..') # We add the parent dir to the path
from src.mercs.core import MERCS
from src.mercs.utils import *

import src.datasets as datasets

/home/elia/Software/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


## Induction

### Importing Data

First, we import the nursery dataset.

In [3]:
train, test = datasets.load_slump()

load_example_dataset is loading fname: ../resc/data/slump_train.csv

load_example_dataset is loading fname: ../resc/data/slump_test.csv



This is a fully numerical dataset

In [4]:
train.head()

Var0      Var1      Var2    Var3      Var4      Var5      Var6  \
0  0.573840  0.424870  0.403846  0.6250  0.315068  0.573267  0.150727   
1  0.109705  0.772021  0.734615  0.2500  0.520548  0.394852  0.403213   
2  0.105485  0.766839  0.734615  0.2375  0.794521  0.386078  0.391737   
3  0.105485  0.766839  0.730769  0.2375  1.000000  0.380228  0.384086   
4  0.071730  0.580311  0.553846  0.7500  0.383562  0.628839  0.066565   

       Var7      Var8      Var9  
0  0.793103  0.724138  0.430576  
1  0.000000  0.000000  0.579342  
2  0.034483  0.000000  0.595549  
3  0.103448  0.025862  0.602080  
4  0.689655  0.758621  0.232946

In [5]:
test.head()

Var0      Var1      Var2    Var3      Var4      Var5      Var6  \
0  0.586498  0.466321  0.446154  0.2500  0.315068  0.473823  0.487376   
1  0.742616  0.580311  0.000000  0.7500  0.383562  0.251536  0.567712   
2  0.780591  0.601036  0.000000  0.4500  0.383562  0.321732  0.659526   
3  0.662447  0.549223  0.523077  0.5875  0.109589  0.114068  0.525631   
4  0.037975  0.549223  0.526923  0.6125  0.109589  0.488447  0.475899   

       Var7      Var8      Var9  
0  0.000000  0.000000  0.650460  
1  0.793103  0.655172  0.265360  
2  0.879310  0.810345  0.304306  
3  0.827586  0.465517  0.582487  
4  0.827586  0.810345  0.258829

### Training

In [6]:
model = MERCS()

In [7]:
ind_parameters = {'ind_type':           'RF',
                  'ind_n_estimators':   10,
                  'ind_max_depth':      4}

sel_parameters = {'sel_type':           'Base',
                  'sel_its':            4,
                  'sel_param':          2}

In [8]:
model.fit(train, **ind_parameters, **sel_parameters)

/home/elia/Software/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py:2428: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return bool(asarray(a1 == a2).all())


In [9]:
codes = model.m_codes

In [10]:
code = [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]

In [14]:
y_pred = model.predict(test)

Predicting q_code: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
Type of numer_res: <class 'list'> 
And type of numer_res[0]: <class 'numpy.ndarray'>
And shape of numer_res[0]: (33, 1)


Type of numer_res: <class 'list'> 
And type of numer_res[0]: <class 'numpy.ndarray'>
And shape of numer_res[0]: (33, 1)


Type of numer_res: <class 'list'> 
And type of numer_res[0]: <class 'numpy.ndarray'>
And shape of numer_res[0]: (33, 1)


Type of numer_res: <class 'list'> 
And type of numer_res[0]: <class 'numpy.ndarray'>
And shape of numer_res[0]: (33, 1)




In [49]:
codes

array([[1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0]])

In [20]:
codes.shape

(20, 10)

In [113]:
mas = np.full(codes.shape[0], 0, dtype=np.int)
mas[0]=1
mas[1]=1
mas[4]=1

In [114]:
mas

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [105]:
q_targ = [7,8,9]

In [106]:
q_targ_attributes_in_selected_models = codes[mas==1,:][:,q_targ]
q_targ_attributes_in_selected_models

array([[0, 0, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [107]:
check = np.where(q_targ_attributes_in_selected_models==1)
q_targ_ok = np.unique(check[1])
q_targ_ok

array([0, 1, 2])

In [109]:
len(q_targ_ok) == len(q_targ)

True

In [116]:
mas_1 = np.array([1,1,0])
mas_2 = np.array([0,1,0])

In [122]:
np.where((mas_1 + mas_2)>0)[0]

array([0, 1])

In [123]:
mas

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [124]:
mas = np.array([1,1,0,0])

In [128]:
mas_2 = np.array([0,0,0,1])

In [129]:
mas_2 = [0,0,0,1]

In [130]:
mas[mas_2>0]=1

TypeError: '>' not supported between instances of 'list' and 'int'

In [127]:
mas

array([1, 1, 0, 1])