# Unittests - mercs/algo/inference

## Imports

In [1]:
# Standard imports
import os
import sys
from os.path import dirname


# Custom imports
root_directory = dirname(os.getcwd())
for dname in {'src'}:
    sys.path.insert(0, os.path.join(root_directory, dname))

from mercs.algo.inference import *
from mercs.utils.utils import encode_attribute

import datasets as ds
from sklearn.preprocessing import Imputer

## Actual Tests

### Perform Imputation

In [2]:
train, test = ds.load_nursery()

load_example_dataset is loading fname: /cw/dtailocal/Files/git/mercs-v5/resc/data/nursery_train.csv

load_example_dataset is loading fname: /cw/dtailocal/Files/git/mercs-v5/resc/data/nursery_test.csv



In [3]:
query_code = [0,-1,-1,0,0,0,0,0,1]

In [4]:
imputator = Imputer(missing_values='NaN',
                    strategy='most_frequent',
                    axis=0)
imputator.fit(train)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='most_frequent',
    verbose=0)

In [5]:
obs = perform_imputation(train, query_code, imputator)

In [6]:
obs.shape

(11680, 9)

In [7]:
train.shape

(11680, 9)

In [8]:
assert train.shape == obs.shape

In [9]:
np.array(query_code)==1

array([False, False, False, False, False, False, False, False,  True])

In [10]:
obs

array([[2., 4., 1., ..., 0., 2., 2.],
       [2., 4., 1., ..., 0., 1., 1.],
       [2., 4., 1., ..., 0., 0., 0.],
       ...,
       [0., 4., 1., ..., 1., 2., 3.],
       [0., 4., 1., ..., 1., 1., 3.],
       [0., 4., 1., ..., 1., 0., 0.]])

In [11]:
missing_attribute_encoding = encode_attribute(0, [1], [2])

In [12]:
boolean_missing = np.array(query_code)== missing_attribute_encoding
boolean_missing

array([False,  True,  True, False, False, False, False, False, False])

In [13]:
missing_count = np.sum(boolean_missing)
missing_count

2

In [14]:
for x in obs[:,boolean_missing].T:
    assert len(np.unique(x)) == 1

In [15]:
len(np.unique(obs[:,np.array(query_code)==-1])) <= missing_count

True

In [16]:
np.unique(obs[:,np.array(query_code)==-1])

array([1., 4.])

In [17]:
def test_perform_imputation():
    # Prelims
    train, test = ds.load_nursery()
    query_code = [0,-1,-1,-1,-1,-1,0,0,1]
    
    imputator = Imputer(missing_values='NaN',
                    strategy='most_frequent',
                    axis=0)
    imputator.fit(train)
    
    # Actual test
    obs = perform_imputation(test, query_code, imputator)
    
    assert test.shape == obs.shape
    assert isinstance(obs, np.ndarray)
    
    boolean_missing = missing_attribute_encoding
    
    for row in obs[:,boolean_missing].T:
        assert len(np.unique(x)) == 1

### Init_predictions

In [18]:
obs = init_predictions(10, 5, type=np.float64)

In [19]:
obs.shape

(10, 5)

In [21]:
obs.dtype == np.float64

True

In [22]:
assert isinstance(obs[0,0], np.float64)

In [ ]:
act_att_idx = [4,5,6]

In [ ]:
np.max(act_att_idx)

In [ ]:
obs.shape[1]

### Update_X

In [30]:
X = np.zeros((100, 4), dtype=np.float64)
Y = np.random.rand(100,2)
act_att_idx = [1,2]

In [31]:
obs = update_X(X, Y, act_att_idx)
obs

array([[0.00000000e+00, 6.05718611e-01, 7.88301472e-01, 0.00000000e+00],
       [0.00000000e+00, 3.10960914e-01, 1.49315912e-01, 0.00000000e+00],
       [0.00000000e+00, 2.18049073e-01, 3.40194977e-01, 0.00000000e+00],
       [0.00000000e+00, 7.56018419e-01, 6.64330171e-02, 0.00000000e+00],
       [0.00000000e+00, 5.30758250e-01, 9.97458888e-01, 0.00000000e+00],
       [0.00000000e+00, 2.37794678e-01, 5.80214702e-01, 0.00000000e+00],
       [0.00000000e+00, 3.12743298e-01, 7.87082174e-01, 0.00000000e+00],
       [0.00000000e+00, 8.08604461e-01, 4.60060939e-01, 0.00000000e+00],
       [0.00000000e+00, 2.52478001e-01, 2.17323879e-01, 0.00000000e+00],
       [0.00000000e+00, 4.70062894e-01, 7.28507809e-01, 0.00000000e+00],
       [0.00000000e+00, 9.75526060e-01, 2.92934149e-01, 0.00000000e+00],
       [0.00000000e+00, 6.27731269e-01, 1.36658308e-01, 0.00000000e+00],
       [0.00000000e+00, 4.31176502e-01, 9.58404287e-01, 0.00000000e+00],
       [0.00000000e+00, 6.65809647e-01, 9.55138851e

In [50]:
test_col_0 = obs[:,act_att_idx[0]] == Y.T[0]
test_col_1 = obs[:,act_att_idx[1]] == Y.T[1]

assert obs.shape == X.shape
assert test_col_0.all()
assert test_col_1.all()


### predict_values_from_numer

In [73]:
nb_atts=4
numer_res = [None]*nb_atts

for i in range(nb_atts):
    numer_res[i]=np.random.rand(100,1)
    
counts = np.random.randint(1,10, size=(nb_atts))

obs = predict_values_from_numer(numer_res, counts)

assert obs.shape[0] == numer_res[0].shape[0]
assert obs.shape[1] == nb_atts
assert isinstance(obs, np.ndarray)

### predict_values_from_proba

In [114]:
nb_atts = 5
nb_classes = 3
nb_samples = 100
proba_res = [None]*nb_atts
lab_res = [None]*nb_atts

for i in range(nb_atts):
    proba_res[i]=np.random.rand(nb_samples, nb_classes)
    
for i in range(nb_atts):
    lab_res[i]=np.random.choice(10, size=nb_classes, replace=False) 

In [98]:
lab_res

[array([8, 5, 9]),
 array([0, 1, 5]),
 array([2, 6, 4]),
 array([5, 0, 4]),
 array([5, 8, 1])]

In [132]:
obs = predict_values_from_proba(proba_res, lab_res)

assert obs.shape == (nb_samples, nb_atts)

for a in range(nb_atts):
    assert np.array_equal(np.unique(obs[:,a]),np.unique(lab_res[a]))

### merge_pred

In [147]:
nb_atts=4
numer_res = [None]*nb_atts

for i in range(nb_atts):
    numer_res[i]=np.random.rand(100,1)

In [148]:
numer_res

[array([[0.20889244],
        [0.19722998],
        [0.28629263],
        [0.24496771],
        [0.75569686],
        [0.59548719],
        [0.53319486],
        [0.87021361],
        [0.12352275],
        [0.12953857],
        [0.67332668],
        [0.47183706],
        [0.09964374],
        [0.74372462],
        [0.49301346],
        [0.60723261],
        [0.95774639],
        [0.98541843],
        [0.9670405 ],
        [0.30374843],
        [0.53954427],
        [0.79674259],
        [0.5222921 ],
        [0.34828827],
        [0.81116799],
        [0.2783769 ],
        [0.08758629],
        [0.2389028 ],
        [0.90150662],
        [0.39203931],
        [0.76634079],
        [0.76696341],
        [0.52465226],
        [0.52617394],
        [0.26734642],
        [0.19935837],
        [0.36375564],
        [0.31261435],
        [0.70644904],
        [0.93834282],
        [0.61071676],
        [0.57323787],
        [0.96348548],
        [0.56278892],
        [0.25665727],
        [0

In [139]:
numer_res[0].shape

(100, 1)

In [157]:
reformat = np.squeeze(np.atleast_2d(numer_res).T)
reformat.shape

(100, 4)

In [159]:
x = reformat[:, [2]]

In [160]:
x.shape

(100, 1)