In [1]:
import numpy as np

In [2]:
a = [8,2,3]
b=[3,4,5]

In [3]:
x=[a,b]

In [4]:
np.concatenate(x)

array([8, 2, 3, 3, 4, 5])

In [5]:
result = np.unique(np.concatenate(x))
#result.sort()
result

array([2, 3, 4, 5, 8])

In [6]:
codes = [[0,0,1]]

In [7]:
nb_atts = 3

In [8]:
errors = [1 for code in codes if len(code) != nb_atts]

In [9]:
errors

[]

In [11]:
len(errors)

0

In [12]:
x = np.array([1,2,3])

In [13]:
x

array([1, 2, 3])

In [15]:
y=np.array(x)
y

array([1, 2, 3])

In [18]:
del x

In [20]:
x = y

In [21]:
x

array([1, 2, 3])

In [22]:
y

array([1, 2, 3])

In [23]:
del y

In [26]:
x

array([1, 2, 3])

In [30]:
u_code = [1,0,0,1]
u_code

[1, 0, 0, 1]

In [31]:
code = np.array(u_code)
code

array([1, 0, 0, 1])

In [32]:
code.shape

(4,)

In [33]:
codes = np.atleast_2d(code)

In [35]:
codes

array([[1, 0, 0, 1]])

In [37]:
codes.shape

(1, 4)

In [43]:
codes[0]

array([1, 0, 0, 1])

In [44]:
help(np.full)

Help on function full in module numpy.core.numeric:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array se

In [47]:
nb_atts = 5
desc_encoding = 0
targ_encoding = 1
q_code = np.full(nb_atts, desc_encoding)
q_code[-1] = targ_encoding  
q_codes = np.atleast_2d(q_code)

In [55]:
code = [0,0,1]

In [57]:
codes = np.atleast_2d(code)

In [58]:
codes[0]

array([0, 0, 1])