In [1]:
import numpy as np

In [2]:
a = [8,2,3]
b=[3,4,5]

In [3]:
x=[a,b]

In [4]:
np.concatenate(x)

array([8, 2, 3, 3, 4, 5])

In [5]:
result = np.unique(np.concatenate(x))
#result.sort()
result

array([2, 3, 4, 5, 8])

In [6]:
codes = [[0,0,1]]

In [7]:
nb_atts = 3

In [8]:
errors = [1 for code in codes if len(code) != nb_atts]

In [9]:
errors

[]

In [11]:
len(errors)

0

In [12]:
x = np.array([1,2,3])

In [13]:
x

array([1, 2, 3])

In [15]:
y=np.array(x)
y

array([1, 2, 3])

In [18]:
del x

In [20]:
x = y

In [21]:
x

array([1, 2, 3])

In [22]:
y

array([1, 2, 3])

In [23]:
del y

In [26]:
x

array([1, 2, 3])

In [30]:
u_code = [1,0,0,1]
u_code

[1, 0, 0, 1]

In [31]:
code = np.array(u_code)
code

array([1, 0, 0, 1])

In [32]:
code.shape

(4,)

In [33]:
codes = np.atleast_2d(code)

In [35]:
codes

array([[1, 0, 0, 1]])

In [37]:
codes.shape

(1, 4)

In [43]:
codes[0]

array([1, 0, 0, 1])

In [44]:
help(np.full)

Help on function full in module numpy.core.numeric:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array se

In [47]:
nb_atts = 5
desc_encoding = 0
targ_encoding = 1
q_code = np.full(nb_atts, desc_encoding)
q_code[-1] = targ_encoding  
q_codes = np.atleast_2d(q_code)

In [65]:
code = [0,0,1]

In [67]:
codes = np.atleast_2d(code)
codes

array([[0, 0, 1]])

In [69]:
for i,v in enumerate(codes[0]):
    print(i,v)

0 0
1 0
2 1


In [70]:
codes[[1]]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [74]:
np.where(codes==1)[1]

array([2])

In [76]:
# Standard imports
import os
import sys
from os.path import dirname


# Custom imports
root_directory = dirname(dirname(os.getcwd()))
for dname in {'src'}:
    sys.path.insert(0, os.path.join(root_directory, dname))

from mercs.algo.inference import *
from mercs.utils.encoding import encode_attribute

import datasets as ds
from sklearn.preprocessing import Imputer

In [107]:
train, test_data_df = ds.load_nursery()
query_code = np.array([0, -1, -1, -1, -1, -1, 0, 0, 1])

In [108]:
imputator = Imputer(missing_values='NaN',
                        strategy='most_frequent',
                        axis=0)

In [109]:
imputator.fit(train)


Imputer(axis=0, copy=True, missing_values='NaN', strategy='most_frequent',
    verbose=0)

In [112]:
assert isinstance(test_data_df, pd.DataFrame)
assert isinstance(query_code, np.ndarray)
assert len(test_data_df.columns.values) == query_code.shape[0]

miss_encoding = encode_attribute(0, [1], [2])
query_data_df = test_data_df.copy()

missing_attributes = np.where(query_code == miss_encoding)[0]
query_data_df.iloc[:, missing_attributes] = np.nan

[1 2 3 4 5]


In [114]:
missing_attributes = np.where(query_code == miss_encoding)[0]
missing_attributes

array([1, 2, 3, 4, 5])

In [95]:
miss_encoding = encode_attribute(0, [1], [2])
query_data_df = test.copy()

missing_attributes = np.where(query_code == miss_encoding)[1]
query_data_df.iloc[:, missing_attributes] = np.nan

In [96]:
missing_attributes

array([1, 2, 3, 4, 5])

In [97]:
query_data_df.iloc[:, missing_attributes] = np.nan

In [115]:
query_data_df

Var0  Var1  Var2  Var3  Var4  Var5  Var6  Var7  Var8
0        2   NaN   NaN   NaN   NaN   NaN     2     2     4
1        2   NaN   NaN   NaN   NaN   NaN     1     0     0
2        2   NaN   NaN   NaN   NaN   NaN     2     2     4
3        2   NaN   NaN   NaN   NaN   NaN     2     2     4
4        2   NaN   NaN   NaN   NaN   NaN     0     0     0
5        2   NaN   NaN   NaN   NaN   NaN     2     1     1
6        2   NaN   NaN   NaN   NaN   NaN     2     2     4
7        2   NaN   NaN   NaN   NaN   NaN     2     0     0
8        2   NaN   NaN   NaN   NaN   NaN     2     0     0
9        2   NaN   NaN   NaN   NaN   NaN     1     2     1
10       2   NaN   NaN   NaN   NaN   NaN     2     1     1
11       2   NaN   NaN   NaN   NaN   NaN     1     2     1
12       2   NaN   NaN   NaN   NaN   NaN     1     0     0
13       2   NaN   NaN   NaN   NaN   NaN     0     2     1
14       2   NaN   NaN   NaN   NaN   NaN     1     2     1
15       2   NaN   NaN   NaN   NaN   NaN     0     0     0
16       2   NaN   NaN   NaN   NaN   NaN     2     0     0
17       2   NaN   NaN   NaN   NaN   NaN     1     1     1
18       2   NaN   NaN   NaN   NaN   NaN     0     1     1
19       2   NaN   NaN   NaN   NaN   NaN     2     1     1
20       2   NaN   NaN   NaN   NaN   NaN     1     1     1
21       2   NaN   NaN   NaN   NaN   NaN     2     0     0
22       2   NaN   NaN   NaN   NaN   NaN     2     2     4
23       2   NaN   NaN   NaN   NaN   NaN     2     0     0
24       2   NaN   NaN   NaN   NaN   NaN     0     1     1
25       2   NaN   NaN   NaN   NaN   NaN     2     1     1
26       2   NaN   NaN   NaN   NaN   NaN     0     2     4
27       2   NaN   NaN   NaN   NaN   NaN     0     1     1
28       2   NaN   NaN   NaN   NaN   NaN     0     0     0
29       2   NaN   NaN   NaN   NaN   NaN     1     1     1
...    ...   ...   ...   ...   ...   ...   ...   ...   ...
1250     0   NaN   NaN   NaN   NaN   NaN     1     1     3
1251     0   NaN   NaN   NaN   NaN   NaN     0     2     1
1252     0   NaN   NaN   NaN   NaN   NaN     0     1     3
1253     0   NaN   NaN   NaN   NaN   NaN     1     1     3
1254     0   NaN   NaN   NaN   NaN   NaN     0     2     3
1255     0   NaN   NaN   NaN   NaN   NaN     2     0     0
1256     0   NaN   NaN   NaN   NaN   NaN     1     2     3
1257     0   NaN   NaN   NaN   NaN   NaN     2     1     3
1258     0   NaN   NaN   NaN   NaN   NaN     2     2     3
1259     0   NaN   NaN   NaN   NaN   NaN     2     0     0
1260     0   NaN   NaN   NaN   NaN   NaN     0     1     3
1261     0   NaN   NaN   NaN   NaN   NaN     1     0     0
1262     0   NaN   NaN   NaN   NaN   NaN     0     0     0
1263     0   NaN   NaN   NaN   NaN   NaN     2     2     3
1264     0   NaN   NaN   NaN   NaN   NaN     2     0     0
1265     0   NaN   NaN   NaN   NaN   NaN     1     1     3
1266     0   NaN   NaN   NaN   NaN   NaN     2     0     0
1267     0   NaN   NaN   NaN   NaN   NaN     1     2     3
1268     0   NaN   NaN   NaN   NaN   NaN     1     2     3
1269     0   NaN   NaN   NaN   NaN   NaN     2     1     3
1270     0   NaN   NaN   NaN   NaN   NaN     1     1     3
1271     0   NaN   NaN   NaN   NaN   NaN     2     0     0
1272     0   NaN   NaN   NaN   NaN   NaN     0     2     3
1273     0   NaN   NaN   NaN   NaN   NaN     2     1     3
1274     0   NaN   NaN   NaN   NaN   NaN     1     2     3
1275     0   NaN   NaN   NaN   NaN   NaN     1     1     3
1276     0   NaN   NaN   NaN   NaN   NaN     2     2     3
1277     0   NaN   NaN   NaN   NaN   NaN     0     2     1
1278     0   NaN   NaN   NaN   NaN   NaN     1     2     3
1279     0   NaN   NaN   NaN   NaN   NaN     0     0     0

[1280 rows x 9 columns]

In [143]:
X = np.zeros((100, 4), dtype=np.float64)
Y = np.random.rand(100, 1)
act_att_idx = np.array([2])

for y_idx, attr_idx in enumerate(act_att_idx):
    X[:, attr_idx] = Y[:, y_idx]

In [144]:
X

array([[0.        , 0.        , 0.45674424, 0.        ],
       [0.        , 0.        , 0.87003297, 0.        ],
       [0.        , 0.        , 0.41262597, 0.        ],
       [0.        , 0.        , 0.76678631, 0.        ],
       [0.        , 0.        , 0.04763266, 0.        ],
       [0.        , 0.        , 0.31649816, 0.        ],
       [0.        , 0.        , 0.23362456, 0.        ],
       [0.        , 0.        , 0.52987946, 0.        ],
       [0.        , 0.        , 0.07515219, 0.        ],
       [0.        , 0.        , 0.9868569 , 0.        ],
       [0.        , 0.        , 0.01328111, 0.        ],
       [0.        , 0.        , 0.20119262, 0.        ],
       [0.        , 0.        , 0.87547346, 0.        ],
       [0.        , 0.        , 0.69486968, 0.        ],
       [0.        , 0.        , 0.76066507, 0.        ],
       [0.        , 0.        , 0.70956809, 0.        ],
       [0.        , 0.        , 0.53579079, 0.        ],
       [0.        , 0.        ,

In [147]:
X = np.zeros((100, 4), dtype=np.float64)
Y = np.random.rand(100, 1)
act_att_idx = np.array([2])



In [154]:
X[:, act_att_idx] = Y

In [155]:
x=None

In [156]:
type(x)

NoneType

In [160]:
x = []

In [162]:
x.append(3)

In [164]:
x

[3]

In [165]:
x.append(4)

In [180]:
m_codes = np.atleast_2d([[0,1,1],[0,1,0],[1,0,0]])

In [191]:
m_codes[1,[1,2]]

array([1, 0])

In [190]:
m_codes[1]

array([0, 1, 0])

In [172]:
m_codes

array([[0, 1, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [175]:
m_targ = np.where(m_codes==1)

In [176]:
m_targ

(array([0, 0, 1, 2]), array([1, 2, 1, 0]))

In [179]:
m_targ[1][np.where(m_targ[0]==1)[0]]

array([1])