# Sandbox

## Imports

In [3]:
import numpy as np

In [13]:
nb_mods, nb_atts = 3, 5
m_codes = np.full((nb_mods, nb_atts), 0)
m_codes[0, -1] = 1
m_codes[1, -2] = 1
m_codes[2, 0:3] = 1
m_codes

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 1, 1, 0, 0]])

In [66]:
fi = np.random.rand(nb_mods, nb_atts)
fi[m_codes != 0] = 0
fi

array([[0.60188505, 0.17107253, 0.47319722, 0.26040707, 0.        ],
       [0.30522709, 0.35192279, 0.73936948, 0.        , 0.36505242],
       [0.        , 0.        , 0.        , 0.60089963, 0.33067662]])

In [69]:
class Yolo():
    def __init__(self):
        self.first_name = 'Yorrick'
        self.last_name = 'Lodewyckx'

In [70]:
yt = Yolo()

In [102]:
attributes(yt)

NameError: name 'attributes' is not defined

In [20]:
avl_m_codes = np.array([[0, 0, 1, 0, 0, 0, 0, 0, 0],
                     [0, 1, 0, 0, 1, 0, 0, 0, 0],
                     [0, 0, 0, 0, 0, 1, 1, 0, 0]])

In [34]:
filt_1 = avl_m_codes[[0,2], [0,2]]
filt_1

array([0, 0])

In [35]:
filt_2 = avl_m_codes[np.ix_([0,2],[1,2])]
filt_2

array([[0, 1],
       [0, 0]])

In [38]:
done = False
x=0
while not done:
    x+=1
    print(x)
    done = x==10

1
2
3
4
5
6
7
8
9
10


In [18]:
steps = list(range(1,5+1))
steps.reverse()
steps

[5, 4, 3, 2, 1]

In [22]:
mas = np.array([-1]*4)
mas

array([-1, -1, -1, -1])

In [26]:
mas[mas_mi==-1]=0
mas[mas_mi==1]=-1
mas

array([ 0,  0, -1, -1])

In [42]:
avl_m_codes = [[0, 0,1],
               [0, 1,1],
               [0,-1,1]]
avl_m_codes = np.array(avl_m_codes)
avl_m_codes

array([[ 0,  0,  1],
       [ 0,  1,  1],
       [ 0, -1,  1]])

SyntaxError: invalid syntax (<ipython-input-57-f4f4e460e4e1>, line 2)

In [54]:
act_atts = np.array([0,1,2])
targ_encoding = 0

In [55]:
np.sum(m_code[act_atts] == targ_encoding)

2

In [51]:
(m_code[act_atts] == targ_encoding).any().astype(int)

1

In [37]:
act_mods_idx = np.where(avl_m_codes[:, [0,1]] == 0)[0]
act_mods_idx

array([0, 0, 1, 2])

In [39]:
unique, counts = np.unique(act_mods_idx, return_counts=True)

In [40]:
counts

array([2, 1, 1])

In [16]:
def mi_setup():
    nb_mods, nb_atts = 3, 5
    nb_qrys = nb_atts # One query per attribute

    m_codes = np.full((nb_mods, nb_atts), 0)
    m_codes[0, -1] = 1
    m_codes[1, -2] = 1
    m_codes[2, 0:3] = 1

    q_codes = np.eye(nb_atts, dtype=int)

    return nb_mods, nb_atts, nb_qrys, m_codes, q_codes

In [17]:
nb_mods, nb_atts, nb_qrys, m_codes, q_codes = mi_setup()

In [21]:
def mi_pred_algo(m_codes, q_codes):

    assert isinstance(m_codes, np.ndarray)
    assert isinstance(q_codes, np.ndarray)
    assert m_codes.shape[1] == q_codes.shape[1]

    # Preliminaries
    nb_mods, nb_atts, nb_qrys, m_desc, m_targ, q_desc, q_targ = _pred_prelims(m_codes,
                                                                              q_codes)
    mas, aas = _init_mas_aas_np(nb_mods, nb_atts, nb_qrys)

    for q_idx in range(nb_qrys):
        aas[q_idx], mas[q_idx] = _mi_pred_algo_single_qry(aas[q_idx],
                                                          mas[q_idx],
                                                          q_desc[q_idx],
                                                          q_targ[q_idx],
                                                          m_codes)

    return mas, aas

def _pred_prelims(m_codes, q_codes):
    """
    Extract some useful quantities every prediction strategy needs

    Parameters
    ----------
    m_codes: np.ndarray, shape (nb_models, nb_atts)
        Two-dimensional np.ndarray where each row encodes a model of the MERCS
        ensemble.
    q_codes: np.ndarray, shape (nb_queries, nb_atts)
        Two-dimensional np.ndarray where each row encodes a query.

    Returns
    -------

    """

    assert isinstance(m_codes, np.ndarray)
    assert isinstance(q_codes, np.ndarray)

    nb_models, nb_atts = m_codes.shape
    nb_queries = q_codes.shape[0]

    m_desc, m_targ, _ = codes_to_query(m_codes)
    q_desc, q_targ, _ = codes_to_query(q_codes)

    return nb_models, nb_atts, nb_queries, m_desc, m_targ, q_desc, q_targ

In [24]:
aas= np.array([-1,-1,-1,0,1])

In [39]:
avl_atts = np.where((0<=aas)&(aas<1))[0]
avl_atts

array([3])

In [19]:
def _mi_pred_algo_single_qry(aas, mas, q_desc, q_targ, m_codes):
    assert isinstance(aas, np.ndarray)
    assert isinstance(mas, np.ndarray)
    assert len(mas.shape) == len(aas.shape) == 1
    
    # Initialization
    aas[q_desc] = 0
    
    # Attribute consideration
    
    
    # Model consideration

    # Model activation
    relevant_models = np.where(m_codes[:, q_targ] == 1)[0]  # Models sharing target with queries
    mas[relevant_models] = 1

    # Att. activation
    aas[q_targ] = 1  # Does not depend on model activation strategy

    return aas, mas

In [23]:
mas, aas = mi_pred_algo(m_codes, q_codes)

NameError: name 'codes_to_query' is not defined